### ISSUE TITLE
[FEATURE] Configure or remember default audio language

### ISSUE THREAD

**Issue by CodeCasterNL** [robvdpol/RaceControl#108]
When you start a new video player in FlyLeaf, it defaults the audio stream to the system's default _input_ language, if available ([`Utils.GetSystemLanguages()`](https://github.com/SuRGeoNix/Flyleaf/blob/ba4cea74d3f8c1052008d2879f8901c5fe887522/FlyleafLib/Utils.cs#L83), [`Default.OpenAudio()`](https://github.com/SuRGeoNix/Flyleaf/blob/ba4cea74d3f8c1052008d2879f8901c5fe887522/FlyleafLib/Plugins/Default.cs#L108)). On my machine, even though its language is English, I have a Dutch input configuration, meaning that the World Feed stream in Race Control starts with Dutch audio, while I'd rather have English commentary.

I'd like to see Race Control remember the language I chose last, and use that as default language for each new player I open, or have a setting somewhere to control the default audio language.

Workaround: save the player layout, which saves the audio stream's languages as well, and then reopen that layout. Usually, I just hit "watch" next to the session I want to watch, though, I don't frequently use layout.

**Comment by robvdpol** [comment]
I think I will add a 'default audio language' setting.

**Comment by CodeCasterNL** [comment]
@robvdpol it's even more complicated than that: now onboard cameras also come with all audio streams. The "undetermined" one is the car sound + driver radio, but each new onboard starts at the default audio stream, repeating the default commentary track with a slight delay.

In other words: start the "World Feed": hear Dutch. Switch it to English, now open a new onboard for any driver: this onboard window will play the Dutch world feed audio stream.

**Comment by robvdpol** [comment]
Yeah, I noticed that as well. I'll default the onboards to the 'undetermined' audio track.

**Comment by CodeCasterNL** [comment]
Looking a bit more at the streams and their data, it would appear that "und" is a safe default stream to pick for any stream, while it exists... Would be a quick fix not requiring much alterations.

**Comment by robvdpol** [comment]
Fixed in next release.

**Comment by CodeCasterNL** [comment]
@robvdpol nice fix, now it starts on English again as well, thanks! [This issue](https://github.com/robvdpol/RaceControl/issues/108#issuecomment-830832074) still exists though:

> The data channels (Driver Tracker, Live Timing) now also come with all audio streams, except for the "und(etermined)" one. They too start blaring commentary.

Perhaps start those feeds on mute, or add a default, silent audio track called "None" or "(None)" to those feeds in particular?
