### ISSUE TITLE
[BUG] Freezes and laptop becomes really hot

### ISSUE THREAD

**Issue by rvdeijk** [robvdpol/RaceControl#264]
I went from version 2.4.1 tot 2.5.2 since nov 7th and I noticed several things:

- When I switch audio, then the video got stuck for a few seconds
- The main feed freezes once in a while (really annoying) and sometimes also the other feeds freezes
- Some bottom parts of the laptop become really really hot

I switched during the race of today (nov 14th) back to 2.4.1 and all of above issues were gone.
No more freezes and laptop cooled down.
Not sure what the difference are between 2.4.1 and 2.5.2, but the latest is not working for me.

Dell Latitude 5491
Windows 10 20H2
64-bit
2.5.2

F1 TV pro account
Netherlands
I'm using the internal player. I have 5 windows. On my TV I have the main feed and on the laptop screen a 2x2 grid: two drivers, pit lane and live timings.

**Comment by SuRGeoNix** [comment]
Hi @rvdeijk, I'm not very familiar with RC's video resolution options but is it possible that you are using higher resolution with 2.5.2 and that's why you are facing this issue?

**Comment by robvdpol** [comment]
@SuRGeoNix Nothing really changed in Race Control except for the extra settings for probesize, analyzeduration and bufferduration.

When I open 6 streams on my laptop everything is fine, Race Control uses only 1% CPU since all the decoding is done on the GPU. GPU load is quite high which causes the fan to spin a bit harder for cooling. Memory is around 900MB which isn't bad either.

I don't think lowering the buffer duration will do much for performance, right? But it's strange that RC 2.4.1 (using Flyleaf 3.2.5) was performing so much better for some people.

**Comment by SuRGeoNix** [comment]
@robvdpol The main difference between 3.2.5 and 3.3.10 is the replacement of SharpDX with Vortice which I don't think that has to do with any of those performance issues. Rather than that... all the other changes are enchantments and better performance overall (eg. pixel shaders). Not sure were to look. I will need more info if Flyleaf causes this, eg:- the memory leaks or GPU memory leaks, or high CPU/GPU etc. They only possible think that comes in mind, is that Video Acceleration fails and uses high CPU and memory instead of GPU, possible with HEVC videos.

**Comment by rvdeijk** [comment]
I could try if I can reproduce it when I watch a race back instead of live. If so, I can check the load difference between 2.4.1 and 2.5.2

**Comment by SuRGeoNix** [comment]
@rvdeijk Yes, that would help to compare the same feeds/videos between those two versions

**Comment by Basdekruijf** [comment]
I have also the freezing problem the last race i had the stream on medium, and the stream had the freeze whit round 70.
I use a hp laptop whit windos 11 home 64 bit also the netherlands and also 2.5.2, i also use a utp cabel for the internet connection.

**Comment by rvdeijk** [comment]
@SuRGeoNix Okay I will paste here some screenshots.
I noticed that since RC 2.5.2 also my NVIDIA GPU is used and the CPU load is a bit higher.
With RC 2.4.1 only the intel GPU is used and the NVIDIA remain idle.

Race Control 2.4.1 overview
![RC_2-4-1](https://user-images.githubusercontent.com/35557458/142002782-a47eba41-59fa-4019-888d-8dca7bc9e9b2.PNG)
Race Control 2.4.1 CPU
![RC_2-4-1_CPU](https://user-images.githubusercontent.com/35557458/142002792-1309ffa6-b825-41bb-94ed-9b67afa4f620.PNG)
Race Control 2.5.2 overview
![RC_2-5-2_CPU](https://user-images.githubusercontent.com/35557458/142002801-0bfe41ad-fab7-478c-95b8-fe2bc61a8346.PNG)
Race Control 2.5.2 GPU Intel
![RC_2-5-2_GPU1](https://user-images.githubusercontent.com/35557458/142002808-4220c2d2-8420-44ed-b05a-06421d5c72c6.PNG)
Race Control 2.5.2 GPU NVIDIA
![RC_2-5-2_GPU2](https://user-images.githubusercontent.com/35557458/142002819-7f1ba745-0b34-4537-8697-6a5e7334a2dd.PNG)
.

**Comment by SuRGeoNix** [comment]
@rvdeijk Thanks for the detailed analysis, that helps a lot. The problem seems to be that when you have more than one GPUs, Flyleaf will not select the right one (better one). So, if we see the results in RC 2.5.2, CPU usage is double and as you mention the video decoding is not happening in GPU. Video acceleration fails as the GPU (nvidia) does not support it. (Which makes sense as that part of the code changed between those two versions, might be a bug with Vortice best adapter selection)

FlyleafLib provides already the list with GPUs and an options to choose which one to use, so @robvdpol could expose FlyleafLib's config generally to the users. However, I will see if possible that the default selection in the library can be improved but there is no easy way of doing this, as a GPU might have better Mem/GPU clock speed but does not support specific video decoding drivers.

@Basdekruijf @erwinvang  Can you please confirm if the issue that you have is because of the same reason? (Having more than one GPUs an RC uses the wrong one)

**Comment by robvdpol** [comment]
I'll try to add a setting so users can choose which GPU to use.

@SuRGeoNix could you point me in the right direction for which config properties I need to use?

**Comment by rvdeijk** [comment]
> Video acceleration fails as the GPU (nvidia) does not support it.

@SuRGeoNix Thanks for the reply and I hope I pointed people to the right direction. I have really no clue why this laptop have the NVIDIA GeForce MX130 if it lacks video accelaration. I think the Intel Graphics UHD 630 could do the job fine. Maybe there are other purposes for the NVIDIA one. Not sure.

> I'll try to add a setting so users can choose which GPU to use.
@robvdpol thanks, that would at least help me to select the right one. But I digged into it and found out, what I believe is the problem. But I can imagine that many people do not have the experience to know which GPU should be selected manually. An automatic way would probably much better for the majority of people. But I understand this is difficult as well.

**Comment by SuRGeoNix** [comment]
@rvdeijk I've created a quick patch [here](https://drive.google.com/file/d/1IgbvEdARBlW5M3gvIvj2gSjpcSWKe4C6/view?usp=sharing)

Can you try replace in v2.5.2 the FlyleafLib.dll with the above and retry?

**Comment by Basdekruijf** [comment]
Our laptop works whit the intel graphics, i look into the gpu use this afternoon.

**Comment by rvdeijk** [comment]
> @rvdeijk I've created a quick patch [here](https://drive.google.com/file/d/1IgbvEdARBlW5M3gvIvj2gSjpcSWKe4C6/view?usp=sharing)
> 
> Can you try replace in v2.5.2 the FlyleafLib.dll with the above and retry?

I tried your quick fix and it fixed the problem :).
The intel GPU is used again and it's decoding and CPU load is back to how RC 2.4.2 behaved.
The NVIDIA remain idle.

Screenshot of RC 2.5.2 with your FlyleafLib.dll
![RC_2-5-2_QuickFix](https://user-images.githubusercontent.com/35557458/142185810-74e50c74-c1d5-44e6-a9ad-605f0d1721e4.PNG)

**Comment by Basdekruijf** [comment]
this is what i have whit 2.5.2 whit out the new flyleaf.

![image](https://user-images.githubusercontent.com/94445718/142193599-499f227b-be92-4012-83e2-456b0274c735.png)

**Comment by rvdeijk** [comment]
> this is what i have whit 2.5.2 whit out the new flyleaf.

I think it's also relevant to make a screenshot when you select the GPU 0 in the task manager.
Probably even better to do the same with with RC 2.4.1
Cause then the developers know if there is a difference in behaviour of those two versions.

**Comment by Basdekruijf** [comment]
This is what i have whit 2.4.1.

![image](https://user-images.githubusercontent.com/94445718/142196976-adfaa61f-a8bc-41ed-9567-3ef86791e839.png)

**Comment by SuRGeoNix** [comment]
@rvdeijk Great news, I will include this patch to the next version

@Basdekruijf You have only one GPU which has the same usage between those two versions. You have freezing issues with 2.5.2 but not with 2.4.1 and even with a single window?

@robvdpol We can skype to fix also the other issue and hopefully you will not have to roll-back to 3.2.5 flyleaflib

**Comment by Basdekruijf** [comment]
@SuRGeoNix i started whit race control whit version 2.5.1 so i dont know iff 2.4.1 freez whit a whole race.

**Comment by SuRGeoNix** [comment]
@Basdekruijf You will need to provide more information so we can resolve also your issue which seems to be different. What freezes means, crashes or freezes and then plays back normally? If crashes can you provide any logs? If freezes how often, with any video any resolution? Do you have issues with the other players (mpv/vlc)?

**Comment by Basdekruijf** [comment]
@SuRGeoNix the stream freezes whit de quality high and medium, the program dont crash and the stream works again when restart the stream. On quality high the stream freezes for 2 a 3 times, whit medium the stream freezes 1 time on the end of the race,
I use the world stream whit dutch audio and when the fan starts blowing the stream freezes, i dith not yet used a nother player yet.

**Comment by SuRGeoNix** [comment]
@Basdekruijf So when the stream freezes you have to restart the stream to play it again, or you can just pause/play and works fine? It is possible that it does not freeze, but it just stops without any reason and you just need to continue playing (which is still an issue but different)

I'm afraid that you will have the same problem with other players as well. It seems that your GPU or memory goes full that's why it freezes. Try to investigate what is going on while it freezes from the task manager and also test other player to ensure that the problem is general and not flyleaf specific.

**Comment by Basdekruijf** [comment]
@SuRGeoNix no its a freeze i cant use pause/play, i must close the window and start the stream again. I gonna try vlc player maybe that works better for me.

**Comment by robvdpol** [comment]
@SuRGeoNix Are you able to release the patched Flyleaf today?

**Comment by SuRGeoNix** [comment]
@robvdpol Yes, just trying to resolve also the downloading issues. Which some were related with this one and others might not.

**Comment by robvdpol** [comment]
Should be fixed in version 2.5.3.

**Comment by rvdeijk** [comment]
@robvdpol I know this issue is closed, but one of my issues still remained with RC 2.5.3, compared to RC 2.4.1:

> * When I switch audio, then the video got stuck for a few seconds

Witch RC 2.4.1 when I switch audio, the video feed continues and the audio comes in when it's ready.
Since RC 2.5.x when I switch audio, the video got stuck (freeze) for 1 sec and then the video continues with the new audio. This is annoying when you have multiple video feeds in sync, but when you want to switch from Dutch to English for example that video feed is not sync anymore compared to the rest.

**Comment by SuRGeoNix** [comment]
@rvdeijk We will need to discuss more about that as the audio switch is different from feed sync. I'm willing to help with a proper feed sync by creating an accurate seeking (additional to the existing keyframe seek). In this way you could just press a button and sync all the windows to each other automatically.

Now for the audio switch, the major difference between the previous version is the buffering that it has been added. So you can download for example the next 5 minutes of the video and seek faster (currently only forward). So when you switch the audio (which is in the same stream with the video) a resync (seek) is required to avoid waiting 5 minutes (or whatever the buffering duration is configured).

**Comment by rvdeijk** [comment]
@SuRGeoNix Hi, well I am talking about when the race is 'live', so there is no seek faster (forward).
I know the same issue appears when I watch back a race. But my point is when the race is live.
During a live session there is no 'sync button'. So what I do is I start the main feed and the pit lane feed.
Then I make sure those to are synced and then I start two driver feeds and make sure those are sync with the pit lane feed.
I do this all within the 5 minutes before the race, once the pit lane feed is enabled.

With RC 2.4.1 I could switch audio during the race, while this did not affect the video. Since RC 2.5.x the video freezes for a short term, which makes my whole sync, not sync.

So probably we have to distinguish 'live' and 'watch back' from each other. Or am I wrong about something.

**Comment by SuRGeoNix** [comment]
Yes, I get your point.  We could have a live seek if ffmpeg provided UTC timestamps (btw, flyleaf supports live seeking as far as the streams provide video segments for e.g. last 2 hours of streaming).

I think then @robvdpol should review it and decide what is better to be implemented. You could get the previous behavior (maybe only for live streams) with the current Flyleaf's version by using a small buffer and by passing resync = false during audio stream switch (openAsync).

**Comment by rvdeijk** [comment]
> Just tested with my Sample version and works fine. Changed the demuxer's bufferduration to 1 second and switched language, the video didn't stop playing and the audio came back after that 1 second

Great, this seems also the behaviour of RC 2.4.1? Then I switched audio and video continued playing and audio arrived indeed a bit later. Which is not a problem. As long as the video continues 👍

**Comment by SuRGeoNix** [comment]
Yes that was the exact behavior on previous version as well. However, this way you loose the meaning of the buffer, not sure what rob want for the RC. Generally, its a good idea to pre-download few minutes of the video to ensure stability and quick seek forward. It's his decision, he could even mix it up eg. Change the buffer duration and openAsync (resync) of audio stream only for live videos and only when the video is near to the end (based on user's seek and live session duration).

**Comment by robvdpol** [comment]
@SuRGeoNix Let's look into this next week.

**Comment by robvdpol** [comment]
@rvdeijk I created issue #269 to track this.
